language: python
python:
  "3.6"

env:
  DJANGO_VERSION=1.11.1

install:
  pip install .
  pip install -r requirements.txt
  pip install -q Django==$DJANGO_VERSION
  python setup.py -q install

script: pytest