language: python

install:
  pip install -r requirements.txt

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - python manage.py runserver &



script:
  - python manage.py test
  - pytest
