language: python
python: 
  - "3.7-dev"

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  

install:
  pip install -r requirements.txt

before_script:
  - chmod +x geckodriver
  - python manage.py migrate
  - python manage.py runserver &



script:
  - python manage.py test
  - pytest
