language: python
python: 
  - "3.7-dev"

install:
  pip install -r requirements.txt

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - chmod +x geckodriver
  - python manage.py migrate
  - python manage.py runserver &



script:
  - sudo python manage.py test
  - sudo pytest
