dist: trusty
language: python
python: 
  - "3.7-dev"

addons:
  chrome: stable
  

install:
  pip install -r requirements.txt

before_script:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - sleep 3
  - chmod +x geckodriver
  - python manage.py migrate
  - python manage.py runserver &



script:
  - python manage.py test
  - pytest
